# development
server:
  # optional, default: 127.0.0.1
  host:
  # optional, default: 4000
  port:
  timezone: UTC
  cluster:  false
  base_url: http://127.0.0.1:4000/

db:
  db: coke-oauth-twitter-dev
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

session:
  # optional, default: sessions
  collection:
  secret: 2e798a6d81f7235c10a93313dc222b5763a62ba6

passport:
  twitter_consumer_key:    00vP72M9U77XjnLDlVvIgA
  twitter_consumer_secret: SJuTp74w3sCwOrIPfllasEPMjU37pgoqFeguP7jZM
  callback_url:            http://127.0.0.1:4000/login/twitter

logs:
  - sys
  - request
  - response
  - error
  - debug

libs:

# libs that must run after server started
started:

aws:
  # your aws key & secret, those must not be empty if you set s3 option to true in assets config
  key:
  secret:
  s3:
    bucket: assets.dev.twitter

